from reportlab.lib.units import cm

# poll constants
OPTION_TEXT_MIN_LENGTH = 3
POLL_NAME_MIN_LENGTH = 3
QUESTION_TEXT_MIN_LENGTH = 3

# reportlab constants
PAGE_MARGINS = 2.5 * cm
REQUIRED_SPACE_AFTER_OPTION = PAGE_MARGINS + 50
REQUIRED_SPACE_AFTER_QUESTION = PAGE_MARGINS + 100
