# Generated by Django 3.1.7 on 2021-05-11 14:10
from django.contrib.auth.models import User
from django.db import migrations

from polls.models import PollState, QuestionType


def load_init_data(apps, schema_editor):
    User.objects.create_user(username='Admin', password='Password')

    PollState.objects.create(name='Draft', description='Author can modify the poll in any way')
    PollState.objects.create(name='Active', description='Participants are filling the poll')
    PollState.objects.create(name='Closed', description='Answers are no longer accepted')

    QuestionType.objects.create(name='Single choice', description='Participant can select a single option')
    QuestionType.objects.create(name='Multi choice', description='Participant can select more options')
    QuestionType.objects.create(name='Text answer', description='Participant writes an answer into the text field')


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_init_data),
    ]
